---
- hosts: all
  become: yes

  vars_files:
    - variables/vars.yml

  roles:
    - { role: change_hostname, tags: ['hostname']}
    - { role: ssh_setup, tags: ['ssh'] }
    - { role: docker, tags: ['pi_setup', 'docker'] }
